/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HinnapakkumineRouteImport } from './routes/hinnapakkumine'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as TeenusedRouteImport } from './routes/teenused'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HinnapakkumineRoute = HinnapakkumineRouteImport.update({
  id: '/hinnapakkumine',
  path: '/hinnapakkumine',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const TeenusedRoute = TeenusedRouteImport.update({
  id: '/teenused',
  path: '/teenused',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hinnapakkumine': typeof HinnapakkumineRoute
  '/kontakt': typeof KontaktRoute
  '/teenused': typeof TeenusedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hinnapakkumine': typeof HinnapakkumineRoute
  '/kontakt': typeof KontaktRoute
  '/teenused': typeof TeenusedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hinnapakkumine': typeof HinnapakkumineRoute
  '/kontakt': typeof KontaktRoute
  '/teenused': typeof TeenusedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hinnapakkumine' | '/kontakt' | '/teenused'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hinnapakkumine' | '/kontakt' | '/teenused'
  id: '__root__' | '/' | '/hinnapakkumine' | '/kontakt' | '/teenused'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HinnapakkumineRoute: typeof HinnapakkumineRoute
  KontaktRoute: typeof KontaktRoute
  TeenusedRoute: typeof TeenusedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hinnapakkumine': {
      id: '/hinnapakkumine'
      path: '/hinnapakkumine'
      fullPath: '/hinnapakkumine'
      preLoaderRoute: typeof HinnapakkumineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teenused': {
      id: '/teenused'
      path: '/teenused'
      fullPath: '/teenused'
      preLoaderRoute: typeof TeenusedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HinnapakkumineRoute: HinnapakkumineRoute,
  KontaktRoute: KontaktRoute,
  TeenusedRoute: TeenusedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
